title: Haifeng Jia 贾海峰
logo: 
email: haifeng.jia@foxmail.com
description: "Ph.D. student"
show_downloads: false
google_analytics: 
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <iconify-icon icon="akar-icons:github-fill" width="24" height="24"></iconify-icon>
    link: https://github.com/haifengjia
  - name: ORCID
    icon: <iconify-icon icon="la:orcid" width="24" height="24"></iconify-icon>
    link: https://orcid.org/0009-0001-7215-9075
  - name: Google Scholar
    icon: <iconify-icon icon="academicons:google-scholar" width="24" height="24"></iconify-icon>
    link: https://scholar.google.com/citations?user=OnkWy7kAAAAJ
  - name: Project Repository
    icon: <iconify-icon icon="mdi:source-repository-multiple" width="24" height="24"></iconify-icon>
    link: https://github.com/haifengjia/haifengjia.github.io

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
