title: Haifeng Jia
logo: /assets/img/20230123_cut.jpg
description: "Ph.D. student @SJTU-NMS-Lab (pre-adm)"
show_downloads: false
google_analytics:
# github_username: haifengjia
theme: jekyll-theme-minimal
