title: Haifeng Jia
logo: /assets/img/me.jpg
description: "Pre-adm Ph.D. student @SJTU-NMS-Lab \n B.S. ECE @SJTU"
show_downloads: false
google_analytics:
github_username: haifengjia
theme: jekyll-theme-minimal
