services:
  - code: VG100
    title: Introduction to Engineering
    role: Teaching Assistant (TA)
    date: 2021 SU
  - code: VE281
    title: Introduction to Data Structures and Algorithms
    role: Teaching Assistant (TA)
    date: 2021 FA
  - code: VE441
    title: App Development for Entrepreneurs
    role: Teaching Assistant (TA)
    date: 2023 SU
  - code: VE586
    title: Advanced Computer Networks
    role: Teaching Assistant (TA)
    date: 2026 SP

academic_services:
  - code: MobiCom'26
    title: Artifact Evaluation Committee (AEC)
    rank: a
    date: 2026
  - code: MEIE'26
    title: Reviewer
    date: 2026
  - code: SenSys'24 RFCom
    title: Reviewer
    rank: b
    date: 2024
