services:
  - code: VG100
    title: Introduction to Engineering
    role: Teaching Assistant (TA)
    date: 2021 SU
  - code: VE281
    title: Introduction to Data Structures and Algorithms
    role: Teaching Assistant (TA)
    date: 2021 FA
  - code: VE441
    title: App Development for Entrepreneurs
    role: Teaching Assistant (TA)
    date: 2023 SU
  - code: VE586
    title: Advanced Computer Networks
    role: Teaching Assistant (TA)
    date: 2026 SP

mentorship:
  - name: Chotiwit Rungrueangwutthinon
    level: Master
    start: 2026
    end: Present
  - name: Xingyuan Ding
    level: Undergrad
    start: 2025
    end: Present
    star: true
  - name: Jishan Ge
    level: Undergrad
    start: 2026
    end: Present
  - name: Jianing Huang
    level: Undergrad
    start: 2025
    end: 2026
    destination: Master@SJTU

academic_services:
  - code: MobiCom'26 AE Committee
    title: Artifact Evaluation Committee (AEC)
    date: 2026
    url: https://www.sigmobile.org/mobicom/2026/artifact_cfp.html
  - code: MEIE'26
    title: Reviewer
    date: 2026
  - code: ArtInHCI'26
    title: Reviewer
    date: 2026
    url: https://www.artinhci.com/DefaultCn.aspx
  - code: SenSys'24 RFCom
    title: Reviewer
    date: 2024
    url: https://xkx-youcha.github.io/RFCom2024/
