services:
  - code: VG100
    title: Introduction to Engineering
    date: 2021 SU
  - code: VE281
    title: Introduction to Data Structures and Algorithms
    date: 2021 FA
  - code: VE441
    title: App Development for Entrepreneurs
    date: 2023 SU
  - code: VE586
    title: Advanced Computer Networks
    date: 2026 SP
